### PR TITLE
Trigger 2.2/2.7

### PR DESCRIPTION
**Pull request by xuezhaojun**
Signed-off-by: xuezhaojun <zxue@redhat.com>

### CODE REVIEW

**Comment by haoqing0110** [comment]
Do we still need this PR? @xuezhaojun

**Comment by xuezhaojun** [comment]
> Do we still need this PR? @xuezhaojun

I think it depends on the repo owner.  If recently no PR is merged, we can use this one to trigger a build.

**Comment by haoqing0110** [comment]
@xuezhaojun thanks, the main branch has some code merged recently, and I will close this PR.

**Pull request closed without merging**
